services:
  profile-svc:
    build: .
    container_name: profile-svc
    environment:
      - KV_VIPER_FILE=./config_docker.yaml
    ports:
      - "8002:8000"
    networks:
      - chains-net

  profile-svc-postgres:
    image: postgres:15
    container_name: profile-svc-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "7002:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chains-net

  profiles-svc-swagger:
    image: swaggerapi/swagger-ui
    container_name: profiles-svc-swagger
    environment:
      - SWAGGER_JSON=/docs/api-bundled.yaml
    volumes:
      - ./docs:/docs:ro
    ports:
      - "5555:8080"
    networks:
      - chains-net


volumes:
  pgdata:
  bundle:

networks:
  chains-net:
    external: true
